when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - release/*
      - renovate/*

variables:
  - &golang_image 'golang:1.22.0'
  - &mysql_image 'mysql:8.2.0'
  - &postgres_image 'postgres:16'

steps:
  "Add vendor":
    image: *golang_image
    commands:
      - go mod vendor

  "Wait databases":
    image: gitnet.fr/deblan/timeout:latest
    commands:
      - /bin/timeout -t 30 -v -c 'while true; do nc -z -v db 3306 2>&1 | grep succeeded && exit 0; sleep 0.5; done'
      - /bin/timeout -t 30 -v -c 'while true; do nc -z -v db 5432 2>&1 | grep succeeded && exit 0; sleep 0.5; done'

  "Fill MySQL"
    image: *mysql_image
    commands:
      - mysql test < tests/mysql_data.sql

  "Run tests":
    image: *golang_image
    commands:
      - go test -v ./...

services:
  service-postgres:
    image: *postgres_image
    ports: ['5432']
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    when: *when

  service-mysql:
    image: *mysql_image
    ports: ['3306']
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
